### ISSUE TITLE
opkg packaging

### ISSUE THREAD

**Issue by nicopace** [libremesh/pirania#11]
opkg packaging

**Comment by nicopace** [comment]
This is the relevant information necessary to implement this:
https://wiki.openwrt.org/doc/devel/packages

Basically:
1. Having a local Makefile that turns the code into executable code
2. Having a Makefile in the lime-packages repo that creates de ipkg

**Comment by luandro** [comment]
Any progress on this @nicopace?

**Comment by aparcar** [comment]
@luandro I created a package, please test it.

**Comment by luandro** [comment]
I'm pretty new to all this. Should I add a new feed to be able to use it with `opkg install`?

**Comment by luandro** [comment]
I need to add `pitbull` to the [PACKAGES](https://github.com/MoinhoDigital/network-profiles/blob/master/moinho/comun/PACKAGES) files in my communities `network-profile`. How do I add the libremesh software feed to opkg? Is that what makes it available?

**Comment by aparcar** [comment]
@luandro please wait a few days until snapshots.libremesh.org eventually works and than it'll be a piece of cake to test

**Comment by luandro** [comment]
Thanks @aparcar, is there somewhere to tack progress for that?

**Comment by aparcar** [comment]
Soon http://snapshots.libremesh.org/ should show created packages and then you can add it as a feed. 
I don't know when the server admin activates the proxy, should happen tonight

**Comment by aparcar** [comment]
@luandro here you go. Currently it's not in stable repos, thereby you have to modify a running router:

* Add the snapshots repository to `/etc/opkg/distfeeds.conf`
`http://snapshots.libremesh.org/snapshots/packages/libremesh/`
Be sure to not use httpS as else your router requires various additional packages to handle encrypted http.

* Add the snapshot public key to `/etc/opkg/keys/`
`https://snapshots.libremesh.org/snapshots/7546f62c3d9f56b1`
Be sure do download it via https to you computer first, then use `scp` to upload it to your router.

* Install pitbull
`opkg update && opkg install pitbull`

These steps are untested but likely work. I haven't tested the pitpull package so please report all further errors to @nicopace

**Comment by aparcar** [comment]
Close this issue in case the installation works

**Comment by luandro** [comment]
Added to `distfeeds.conf` like this: `src/gz packages http://snapshots.libremesh.org/snapshots/packages/libremesh/`.

Added the key thru `scp`.  Did a `opkg update`, which seems to have worked:

```
Downloading http://snapshots.libremesh.org/snapshots/packages/libremesh/Packages.gz
Updated list of available packages in /var/opkg-lists/update
Downloading http://snapshots.libremesh.org/snapshots/packages/libremesh/Packages.sig
Signature check passed.
```

But always get `Unknown package` when trying to install `pitbull` or `lime-pitbull`.

Am I missing something?

**Comment by aparcar** [comment]
Good call, typo in PKGNAME and thereby it's currently called `pitpul`

Once https://github.com/libremesh/lime-packages/pull/377 is merged ~15 minutes later the correct pitBull package should be there!

**Comment by luandro** [comment]
Worked! @nicopace can close this.
