### ISSUE TITLE
Multi-node captive portal sync

### ISSUE THREAD

**Issue by nicopace** [libremesh/pirania#15]
Sync captive portals using batman-adv Alfred/bmx6-sms

**Comment by luandro** [comment]
Me and @gmarcos87 began to work on the Alfred scripts [here](https://github.com/luandro/libre-portal/blob/master/libremesh/files/etc/alfred/alf-voucher.lua). With some guidance we I can continue working on it.

**Comment by luandro** [comment]
Now works using [shared-state](https://github.com/libremesh/lime-packages/tree/master/packages/shared-state).
