### ISSUE TITLE
'No internet’ strategy

### ISSUE THREAD

**Issue by nicopace** [libremesh/pirania#17]
Strategy when there is no gateway and you want the network to work without Internet

**Comment by brunovianna** [comment]
I don't know if this should be part of the captive portal or a separate packet. The thing is, when there is not internet there is no route out, so no way of finding the gateway. I think there should be a redirect page where there user is taken when there is no internet, which could be defined in the chef. This page would point to the resources available within the local network.

**Comment by nicopace** [comment]
We are rethinking the whole chef thing, so we don't need chef for many of this things.
The idea about a no internet policy, is to be able to use the captive portal as a catch-all way of redirecting users somewhere.
Where they are redirected will be configurable, and it will have a local sane default

**Comment by brunovianna** [comment]
2 cents about chef --- it makes the whole libremesh concept really accessible for people who can't do CLI or linux. No matter how you rethink, please keep it as a web interface where people can create their networks! :)

**Comment by nicopace** [comment]
On Tue, 2017-06-06 at 14:20 -0700, bruno vianna wrote:
> 2 cents about chef --- it makes the whole libremesh concept really
> accessible for people who can't do CLI or linux. No matter how you
> rethink, please keep it as a web interface where people can create
> their networks! :)

Well... actually if we manage to do all what we are doing... you won't
need Chef or lime-sdk or any of those... it will be self-configured !!!
(more news soon, or ping me if you have coding skills and a lot of
spare time to code :) ).

**Comment by aparcar** [comment]
@nicopace could you tell some more Details?

**Comment by nicopace** [comment]
@aparcar you are a little anxious :)
News will appear in this repo:
https://github.com/libremesh/FirstBootWizard
The idea is to have one tool that configures a node to work in a certain mesh easily.

**Comment by aparcar** [comment]
@nicopace always ;) Anyway I think our concepts won't interfere

**Comment by henmohr** [comment]
check wan interface for a valid ip adress? watch outgoin and incoming connections?

**Comment by luandro** [comment]
If there's no internet the captive-portal will run anyway. And the local mesh network traffic still works.

If that's not what this issue is about, please re-open.

**Comment by patogit** [comment]
any chance that this issue https://github.com/libremesh/lime-packages/issues/403 can be handled in pirania?

**Comment by luandro** [comment]
Unfortunately I don't think there's anything we can do about that. I might be mistaken. Maybe @altergui or @gmarcos87 could clarify better.
