### ISSUE TITLE
Config external captive portal

### ISSUE THREAD

**Issue by nicopace** [libremesh/pirania#18]
config to setup an external captive portal

**Comment by luandro** [comment]
Should there be in additional to the [captive-portal](https://github.com/libremesh/pitbull/blob/master/files/usr/bin/captive-portal) script, which takes care of adding the ipv4 and ipv6 adresses and setting the `iptables` rules?

**Comment by altergui** [comment]
This is almost done, basically this file can redirect the browser to any url:
https://github.com/libremesh/pirania/blob/0a8091c51f5c627f06d29807f8d98157adae9f6c/files/www/pirania-redirect/index.html
right now it is hardcoded (very ugly) to redirect to http://thisnode.info/pirania/ , but it could be parametrized somehow
