### ISSUE TITLE
auth_voucher doesn't work

### ISSUE THREAD

**Issue by luandro** [libremesh/pirania#20]
Was finally able to get `pitbull` installed. Been trying to test it out and I noticed that although `add_voucher` works in adding a new voucher profile, `auth_voucher` doesn't work in adding a new mac address to a profile.

If I have a userId `luandro` it should be used like this `voucher auth_voucher d0:a6:37:e8:1a:08 luandro` right?

**Comment by altergui** [comment]
I have the feeling that i fixed this in https://github.com/libremesh/pirania/commit/19e587c4f4102b35eb3ed1d3dad9a61005eeef75#diff-cb45971b4caefbb69397de878c34a151
