### ISSUE TITLE
Captive portal doesn't open on mobile

### ISSUE THREAD

**Issue by luandro** [libremesh/pirania#21]
Testing on an Android phone v6.0 and captive portal doesn't open and loading pages on Chrome simply shows no connection.

The ideal interaction would be to pop open the captive portal.

**Comment by altergui** [comment]
Fixed with major rewrite of iptables integration https://github.com/libremesh/pirania/commit/211f2e591602bf3ccf445105b61d70c5a4f237b8#diff-5c10e46169eb52c76ce457ba12acc4aa
