### ISSUE TITLE
provide a way to authorize oneself (enter a voucher) without javascript

### ISSUE THREAD

**Issue by altergui** [libremesh/pirania#26]
here with @hiurequeiroz we just came across an android device 4.4.4 that could not display the bundle developed by @luandro

browsing to http://thisnode.info/pirania/ just showed a blank page (it did not even say ```You need to enable JavaScript to run this app.```). Disabling javascript in the android browser did correctly show the ```You need to enable JavaScript to run this app.```, indicating that the blank page is due to a failed javascript (quite possibly an outdated browser. But we'll definitely find this in the wild)

We need to provide a way to authorize oneself (enter a voucher) without javascript

details:
model: G620S-L01
version: Android 4.4.4

**Comment by luandro** [comment]
In this case another device with Javascript should enable for the device.
