### ISSUE TITLE
UI internacionalization

### ISSUE THREAD

**Issue by luandro** [libremesh/pirania#30]
The captive-portal UI in many languages. At least English, Spanish and Portuguese to start off.

**Comment by patogit** [comment]
Did you put all languages in one file for ease of programming? I think translation will be easier if each language is in a separate file, though maybe translatewiki.net can handle the single-file format.

**Comment by luandro** [comment]
Current internationalization is very basic, as the portal is very simple JS, so it currently simply lives in one single JS file ([int.js](https://github.com/libremesh/pirania/blob/master/pirania-app/files/www/portal/js/int.js)). When we get to #19 LimeApp has a better structure for translations.
