### ISSUE TITLE
As a Network Administrator I want to issue batches of vouchers to facilitate their distribution among the Community through non-technical members

### ISSUE THREAD

**Issue by nicopace** [libremesh/pirania#5]
One way to do this is to generate a random group of vouchers that all share the same characteristics.
There must be also a way to see which ones where used.

**Comment by nicopace** [comment]
#9

**Comment by nicopace** [comment]
- [ ] #9 Equal Rating

**Comment by luandro** [comment]
Done with `create_many_vouchers` command.
